#!/usr/bin/env python3
"""Merge canonical recurring-character arc content into the runtime content bundle.

Idempotent + reproducible: reads the canonical patterns-of-choice repo (specs are
the source of truth) and writes the arc-dependent keys into
runtime/content-bundle.v0.1.json WITHOUT touching the existing quickfires /
values / narratives. Re-run whenever the canonical arc, its climax, or the H8
pairing change.

Adds three keys:
  arcs          : [ arc-biscuit ]                     (full arc, inline build-up beats)
  arcScenarios  : { "narr-allocation-008": <narrative> }  (scenarios referenced by
                  high_stakes beats via scenario_ref; kept OUT of the daily
                  narrative rotation, which only reads `narratives`)
  h8Probes      : [ { pair, abstract item, narrative signal } ]  (sets up the on-device
                  H8b abstract-vs-narrative divergence read)

Canonical repo path: $POC_CANON, else the sibling ../patterns-of-choice.
"""
import json
import os
from pathlib import Path

HERE = Path(__file__).resolve()
DALIU_ROOT = HERE.parents[2]                      # .../Code/daliu.github.io
CANON = Path(os.environ.get("POC_CANON", HERE.parents[3] / "patterns-of-choice"))
BUNDLE = HERE.parent / "content-bundle.v0.1.json"


def load(p):
    with open(p) as f:
        return json.load(f)


def main():
    assert CANON.exists(), f"canonical repo not found: {CANON} (set POC_CANON)"
    bundle = load(BUNDLE)

    arc = load(CANON / "scenarios/arcs/arc-biscuit.json")

    # Collect every scenario referenced by a high_stakes beat's scenario_ref.
    arc_scenarios = {}
    for beat in arc["beats"]:
        ref = beat.get("scenario_ref")
        if ref:
            arc_scenarios[ref] = load(CANON / f"scenarios/sample/{ref}.json")

    # H8 probe pairs that this arc participates in (build the on-device read input).
    pairs = load(CANON / "scenarios/h8-probe-pairs.json")["pairs"]
    arc_pair_ids = {b.get("pairs_with") for b in arc["beats"] if b.get("pairs_with")}
    h8_probes = []
    for p in pairs:
        if p["pair_id"] not in arc_pair_ids:
            continue
        aref = p["abstract_ref"]
        qf = load(CANON / f"scenarios/sample/{aref['scenario_id']}.json")
        item = next((it for it in qf["items"] if it["id"] == aref["item_id"]), None)
        assert item, f"abstract item {aref['item_id']} not found in {aref['scenario_id']}"
        h8_probes.append({
            "pair_id": p["pair_id"],
            "domain": p["domain"],
            "stakes_level": p["stakes_level"],
            "abstract": {
                "scenario_id": aref["scenario_id"],
                "item_id": aref["item_id"],
                "prompt": item["prompt"],
                "options": item["options"],
            },
            "narrative": {
                "scenario_id": p["narrative_ref"]["scenario_id"],
                "signal": p["narrative_ref"]["signal"],
            },
        })

    bundle["arcs"] = [arc]
    bundle["arcScenarios"] = arc_scenarios
    bundle["h8Probes"] = h8_probes
    bundle["_provenance"] = (
        bundle.get("_provenance", "").split(" | arcs:")[0]
        + " | arcs: generated by runtime/build-arc-bundle.py from canonical "
        "scenarios/arcs/arc-biscuit.json + referenced climax + h8-probe-pairs.json"
    )

    with open(BUNDLE, "w") as f:
        json.dump(bundle, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"merged into {BUNDLE.name}:")
    print(f"  arcs: {[a['arc_id'] for a in bundle['arcs']]} "
          f"({len(arc['beats'])} beats)")
    print(f"  arcScenarios: {list(arc_scenarios)}")
    print(f"  h8Probes: {[h['pair_id'] for h in h8_probes]}")


if __name__ == "__main__":
    main()
