#!/usr/bin/env python3
"""Generate the Patterns of Choice "research program" card grid from the
canonical manifest in the patterns-of-choice repo, and inject it into
patterns-of-choice/index.html between the auto-gen markers.

Why this exists: the public writeup kept drifting from the experiment as the
research loop shipped new branches (H10, H11, H-A2, ...), each requiring a
hand-edited HTML card. The experiment repo now owns its public-presentation
data in patterns-of-choice/research-program.json; when a branch ships, add one
entry there (same commit as the branch) and re-run this. No more hand-crafted
cards, no more drift.

Manifest resolution order:
  1. $POC_REPO/research-program.json            (env override)
  2. ../patterns-of-choice/research-program.json (sibling checkout - the default)
  3. https://raw.githubusercontent.com/daliu/patterns-of-choice/main/research-program.json  (fallback)

Usage:
    python scripts/build_patterns_program.py            # regenerate + write
    python scripts/build_patterns_program.py --check    # verify in sync; exit 1 if the site has drifted

Run manually for now; could be wired into publish_daily.py (or a CI check)
later, the same way build_status.py is.
"""

import argparse
import json
import os
import sys
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(REPO, "patterns-of-choice", "index.html")

RAW_MANIFEST = (
    "https://raw.githubusercontent.com/daliu/patterns-of-choice/main/research-program.json"
)
DEFAULT_SPEC_BASE = "https://github.com/daliu/patterns-of-choice/blob/main/"

BEGIN_MARK = "<!-- BEGIN auto:research-program-grid"
END_MARK = "<!-- END auto:research-program-grid -->"
BEGIN_LINE = (
    "  " + BEGIN_MARK + " — generated by daliu.github.io/scripts/"
    "build_patterns_program.py from patterns-of-choice/research-program.json; "
    "do not hand-edit -->"
)
END_LINE = "  " + END_MARK

REQUIRED_KEYS = ("id", "question", "status", "spec", "blurb")


def load_manifest():
    candidates = []
    if os.environ.get("POC_REPO"):
        candidates.append(os.path.join(os.environ["POC_REPO"], "research-program.json"))
    candidates.append(
        os.path.join(os.path.dirname(REPO), "patterns-of-choice", "research-program.json")
    )
    for path in candidates:
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                return json.load(fh), path
    with urllib.request.urlopen(RAW_MANIFEST, timeout=15) as resp:  # noqa: S310 (trusted own repo)
        return json.loads(resp.read().decode("utf-8")), RAW_MANIFEST


def esc(text):
    """Minimal HTML-text escaping. Unicode dashes/quotes are emitted as-is
    (the page is UTF-8); only the structural characters need escaping."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render_grid(manifest):
    base = manifest.get("spec_base", DEFAULT_SPEC_BASE)
    cards = manifest["cards"]
    if not cards:
        raise SystemExit("research-program.json has no cards")
    lines = ['  <div class="domain-grid">']
    for i, c in enumerate(cards):
        missing = [k for k in REQUIRED_KEYS if not c.get(k)]
        if missing:
            raise SystemExit(f"card #{i} missing keys: {missing}")
        header = esc(f"{c['id']} · {c['question']}")
        status = esc(c["status"])
        blurb = esc(c["blurb"])
        lines.append('    <div class="domain">')
        lines.append(
            f'      <strong>{header}</strong> '
            f'<span style="color: var(--muted); font-weight: 400;">— {status}</span>'
        )
        lines.append(
            f'      <p>{blurb} <a href="{base}{c["spec"]}">The spec →</a></p>'
        )
        lines.append("    </div>")
    lines.append("  </div>")
    return "\n".join(lines)


def build_block(manifest):
    return BEGIN_LINE + "\n" + render_grid(manifest) + "\n" + END_LINE


def splice(html, block):
    if BEGIN_MARK not in html or END_MARK not in html:
        raise SystemExit(
            f"markers not found in {TARGET} - add the BEGIN/END "
            f"auto:research-program-grid comments around the grid first"
        )
    b = html.index(BEGIN_MARK)
    line_start = html.rfind("\n", 0, b) + 1  # start of the BEGIN line (keep its indent uniform)
    e = html.index(END_MARK) + len(END_MARK)
    return html[:line_start] + block + html[e:]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify the site is in sync with the manifest; exit 1 if drifted")
    args = ap.parse_args()

    manifest, src = load_manifest()
    block = build_block(manifest)
    with open(TARGET, encoding="utf-8") as fh:
        html = fh.read()
    new_html = splice(html, block)
    n = len(manifest["cards"])

    if args.check:
        if new_html != html:
            print(f"DRIFT: {TARGET} is out of sync with {src}. "
                  f"Run `python scripts/build_patterns_program.py` to regenerate.", file=sys.stderr)
            return 1
        print(f"in sync: {n} cards, source {src}")
        return 0

    if new_html == html:
        print(f"no change: {n} cards already current ({src})")
        return 0
    with open(TARGET, "w", encoding="utf-8") as fh:
        fh.write(new_html)
    print(f"wrote {TARGET}: {n} cards from {src}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
