#!/usr/bin/env python3
"""Generate the editorial content of the /now/ page from the Obsidian vault and
splice it into now/index.html between the `auto:now-content` markers.

Why this exists: /now/ was a hand-written HTML page that drifted from Dave's
actual current status. Now the single source of truth is wiki/now.md in the
vault — edit that note, bump its `updated:` frontmatter date, and the daily sync
re-renders this page. The page chrome (<head>, <nav>, <footer>) is NOT touched;
only the inner content region between the markers is regenerated, so an unrelated
nav change (e.g. adding a "Blog" link) never conflicts with this builder.

Source resolution:
  wiki/now.md under --vault (default: ~/Documents/Remote Vault)

Rendering contract (must stay visually identical to the pre-change page):
  - Fixed chrome inside the markers — the "Now ●" title, the nownownow subtitle,
    and the "what is a /now/ page" callout — is emitted by this script verbatim.
  - Each `## Heading` in now.md becomes an uppercase <h2> section.
  - Under a heading, each top-level block (a paragraph, or a single top-level
    `- ` bullet) becomes one `.card` containing a single <p>. Markdown inline
    formatting (**bold**, [links](url), `code`) is rendered inside the <p>.
  - "Last updated" is stamped from frontmatter `updated` (NOT build time), so the
    output is idempotent and the date is honest (it reflects Dave's last edit).

Usage:
    python scripts/build_now.py            # regenerate + write (idempotent)
    python scripts/build_now.py --check    # verify in sync; exit 1 if drifted
"""

import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(REPO, "now", "index.html")
DEFAULT_VAULT = os.path.expanduser("~/Documents/Remote Vault")

BEGIN_MARK = "<!-- BEGIN auto:now-content"
END_MARK = "<!-- END auto:now-content -->"
BEGIN_LINE = (
    "  " + BEGIN_MARK + " — generated by daliu.github.io/scripts/"
    "build_now.py from wiki/now.md; do not hand-edit -->"
)
END_LINE = "  " + END_MARK

# Fixed chrome that lives INSIDE the markers but is not part of the editorial
# markdown — kept here verbatim so the top of the page renders identically.
INTRO = (
    '  <h1>Now <span class="now-dot">●</span></h1>\n'
    '  <p class="subtitle">A short status of what I\'m currently working on, in '
    'the spirit of <a href="https://nownownow.com/about" style="color: '
    'var(--accent);">nownownow.com</a>.</p>\n'
    '\n'
    '  <p class="what-this">A <em>/now/</em> page is the indieweb\'s answer to '
    '"what\'s up?" — a single-page snapshot meant to be shorter than a blog and '
    'more current than an "about" page. Updated as needed; not auto-generated.</p>'
)


def parse_frontmatter(content):
    """Extract YAML frontmatter from markdown (no PyYAML dependency).

    Mirrors build_graph.py's parser: supports simple `key: value` pairs and
    `key:` followed by `- item` lists. Returns (frontmatter_dict, body).
    """
    if not content.startswith("---"):
        return {}, content
    end = content.find("---", 3)
    if end == -1:
        return {}, content
    fm_text = content[3:end]
    body = content[end + 3 :]
    fm = {}
    current_key = None
    current_list = None
    for line in fm_text.strip().split("\n"):
        list_match = re.match(r"^\s+-\s+(.+)", line)
        if list_match and current_key:
            if current_list is None:
                current_list = []
                fm[current_key] = current_list
            current_list.append(list_match.group(1).strip().strip('"').strip("'"))
            continue
        kv_match = re.match(r"^(\w[\w_]*)\s*:\s*(.*)", line)
        if kv_match:
            current_key = kv_match.group(1)
            val = kv_match.group(2).strip().strip('"').strip("'")
            current_list = None
            if val == "" or val == "[]":
                fm[current_key] = []
                current_list = fm[current_key]
            elif val.startswith("[") and val.endswith("]"):
                fm[current_key] = [
                    v.strip().strip('"').strip("'")
                    for v in val[1:-1].split(",")
                    if v.strip()
                ]
            else:
                fm[current_key] = val
    return fm, body


def _strip_comments(body):
    """Drop HTML comments (the convention note) from the markdown body."""
    return re.sub(r"<!--.*?-->", "", body, flags=re.S)


def _render_inline(md, text):
    """Render a single block of inline markdown to the <p> inner HTML the page
    uses. We render then unwrap the single <p> markdown produces."""
    html = md.convert(text.strip())
    html = html.strip()
    # markdown wraps a single paragraph in <p>...</p>; unwrap to reuse our own <p>.
    if html.startswith("<p>") and html.endswith("</p>"):
        html = html[len("<p>"):-len("</p>")]
    return html


def _split_blocks(section_body):
    """Split a section's body into card blocks. A block is either a paragraph
    (text separated by blank lines) or a single top-level `- ` bullet."""
    blocks = []
    for chunk in re.split(r"\n\s*\n", section_body.strip()):
        chunk = chunk.strip()
        if not chunk:
            continue
        # A top-level bullet list: each `- ` item is its own card.
        if re.match(r"^-\s+", chunk) and "\n-" in ("\n" + chunk):
            for item in re.split(r"\n(?=-\s+)", chunk):
                item = re.sub(r"^-\s+", "", item.strip())
                if item:
                    blocks.append(item)
        elif chunk.startswith("- "):
            blocks.append(re.sub(r"^-\s+", "", chunk))
        else:
            blocks.append(chunk)
    return blocks


def render_content(fm, body):
    """Render the frontmatter + markdown body into the inner HTML for the
    content region (between the markers)."""
    try:
        import markdown
    except ImportError as exc:  # pragma: no cover - exercised via message text
        raise SystemExit(
            "build_now.py requires the `markdown` library "
            "(`pip install markdown`); import failed: " + str(exc)
        )
    md = markdown.Markdown(extensions=[])

    body = _strip_comments(body)

    lines = [INTRO]

    # Split the body into `## Heading` sections, preserving order.
    parts = re.split(r"^##\s+(.+?)\s*$", body, flags=re.M)
    # parts[0] is any preamble before the first heading (ignored); then pairs of
    # (heading, section_body).
    for i in range(1, len(parts), 2):
        heading = parts[i].strip()
        section_body = parts[i + 1] if i + 1 < len(parts) else ""
        md.reset()
        lines.append(f'\n  <h2>{heading}</h2>')
        for block in _split_blocks(section_body):
            md.reset()
            inner = _render_inline(md, block)
            lines.append('  <div class="card">')
            lines.append(f'    <p>{inner}</p>')
            lines.append('  </div>')

    updated = fm.get("updated", "")
    label = _updated_label(updated)
    lines.append(f'\n  <p class="meta">Last updated: {label}.</p>')
    return "\n".join(lines)


def _updated_label(updated):
    """Render the frontmatter `updated` date (YYYY-MM-DD) as 'Month YYYY',
    matching the page's existing 'Last updated: June 2026.' style. Falls back to
    the raw string if it isn't a parseable date."""
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})$", str(updated).strip())
    if not m:
        return str(updated).strip()
    year, month, _ = m.groups()
    months = [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ]
    return f"{months[int(month) - 1]} {year}"


def build_block(fm, body):
    return BEGIN_LINE + "\n" + render_content(fm, body) + "\n" + END_LINE


def splice(html, block):
    if BEGIN_MARK not in html or END_MARK not in html:
        raise SystemExit(
            f"markers not found in {TARGET} - add the BEGIN/END "
            f"auto:now-content comments around the content region first"
        )
    b = html.index(BEGIN_MARK)
    line_start = html.rfind("\n", 0, b) + 1  # keep the BEGIN line's indentation uniform
    e = html.index(END_MARK) + len(END_MARK)
    return html[:line_start] + block + html[e:]


def load_source(vault):
    path = os.path.join(vault, "wiki", "now.md")
    if not os.path.exists(path):
        raise SystemExit(f"source not found: {path}")
    with open(path, encoding="utf-8") as fh:
        content = fh.read()
    return content, path


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--vault", default=DEFAULT_VAULT, help="Path to Obsidian vault")
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify now/index.html is in sync with wiki/now.md; exit 1 if drifted",
    )
    args = ap.parse_args()

    content, src = load_source(args.vault)
    fm, body = parse_frontmatter(content)

    # Overwrite guard (mirrors build_graph.py): never blank the content region on
    # an empty/failed source read. If now.md has no headings/body, refuse rather
    # than wiping the page's editorial content.
    if not body.strip() or "##" not in body:
        raise SystemExit(
            f"refusing to render: {src} has no section content "
            f"(empty or missing '## ' headings). Content region left untouched."
        )

    block = build_block(fm, body)
    with open(TARGET, encoding="utf-8") as fh:
        html = fh.read()
    new_html = splice(html, block)

    if args.check:
        if new_html != html:
            print(
                f"DRIFT: {TARGET} is out of sync with {src}. "
                f"Run `python scripts/build_now.py` to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"in sync: source {src}")
        return 0

    if new_html == html:
        print(f"no change: /now/ already current ({src})")
        return 0
    with open(TARGET, "w", encoding="utf-8") as fh:
        fh.write(new_html)
    print(f"wrote {TARGET} from {src}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
