#!/usr/bin/env python3
"""Generate the Patterns of Choice "research program" card grid from the
canonical manifest in the patterns-of-choice repo, and inject it into
patterns-of-choice/index.html between the auto-gen markers.

Why this exists: the public writeup kept drifting from the experiment as the
research loop shipped new branches (H10, H11, H-A2, ...), each requiring a
hand-edited HTML card. The experiment repo now owns its public-presentation
data in patterns-of-choice/research-program.json; when a branch ships, add one
entry there (same commit as the branch) and re-run this. No more hand-crafted
cards, no more drift.

Manifest resolution order:
  1. $POC_REPO/research-program.json            (env override)
  2. ../patterns-of-choice/research-program.json (sibling checkout - the default)
  3. https://raw.githubusercontent.com/daliu/patterns-of-choice/main/research-program.json  (fallback)

Usage:
    python scripts/build_patterns_program.py            # regenerate + write
    python scripts/build_patterns_program.py --check    # verify in sync; exit 1 if the site has drifted

--check also confirms every card's spec file exists — a dangling `The spec →`
link is a live 404 on the public page. That part runs only against a local
checkout (the spec files live in the sibling patterns-of-choice repo, next to
the manifest); over --remote there are no local files to stat, so it's skipped.

Wired into the daily publish: publish_daily.py:refresh_patterns_program runs
this with --remote (best-effort — a failure there never aborts the run) and
stages the regenerated index.html, so the public grid tracks the manifest with
zero hand-editing. Run --check locally or from CI to catch drift or a dangling
spec link before it ships.
"""

import argparse
import json
import os
import sys
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(REPO, "patterns-of-choice", "index.html")

RAW_MANIFEST = (
    "https://raw.githubusercontent.com/daliu/patterns-of-choice/main/research-program.json"
)
DEFAULT_SPEC_BASE = "https://github.com/daliu/patterns-of-choice/blob/main/"

BEGIN_MARK = "<!-- BEGIN auto:research-program-grid"
END_MARK = "<!-- END auto:research-program-grid -->"
BEGIN_LINE = (
    "  " + BEGIN_MARK + " — generated by daliu.github.io/scripts/"
    "build_patterns_program.py from patterns-of-choice/research-program.json; "
    "do not hand-edit -->"
)
END_LINE = "  " + END_MARK

REQUIRED_KEYS = ("id", "question", "status", "spec", "blurb")


def load_manifest(remote=False):
    if not remote:
        candidates = []
        if os.environ.get("POC_REPO"):
            candidates.append(os.path.join(os.environ["POC_REPO"], "research-program.json"))
        candidates.append(
            os.path.join(os.path.dirname(REPO), "patterns-of-choice", "research-program.json")
        )
        for path in candidates:
            if os.path.exists(path):
                with open(path, encoding="utf-8") as fh:
                    return json.load(fh), path
    with urllib.request.urlopen(RAW_MANIFEST, timeout=15) as resp:  # noqa: S310 (trusted own repo)
        return json.loads(resp.read().decode("utf-8")), RAW_MANIFEST


def esc(text):
    """Minimal HTML-text escaping. Unicode dashes/quotes are emitted as-is
    (the page is UTF-8); only the structural characters need escaping."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def missing_spec_files(manifest, src):
    """Return [(id, spec), ...] for cards whose linked spec file is absent.

    Only meaningful when the manifest came from a local checkout — the spec
    files are siblings of the manifest. When it was fetched over the network
    (the daily run's --remote path) there is nothing local to stat, so this
    returns [] and the caller treats the check as skipped."""
    if not os.path.isfile(src):  # remote URL (or vanished) — no local files to verify
        return []
    base_dir = os.path.dirname(os.path.abspath(src))
    missing = []
    for c in manifest["cards"]:
        spec = c.get("spec")
        if spec and not os.path.isfile(os.path.join(base_dir, spec)):
            missing.append((c.get("id", "?"), spec))
    return missing


def render_grid(manifest):
    base = manifest.get("spec_base", DEFAULT_SPEC_BASE)
    cards = manifest["cards"]
    if not cards:
        raise SystemExit("research-program.json has no cards")
    lines = ['  <div class="domain-grid">']
    for i, c in enumerate(cards):
        missing = [k for k in REQUIRED_KEYS if not c.get(k)]
        if missing:
            raise SystemExit(f"card #{i} missing keys: {missing}")
        header = esc(f"{c['id']} · {c['question']}")
        status = esc(c["status"])
        blurb = esc(c["blurb"])
        lines.append('    <div class="domain">')
        lines.append(
            f'      <strong>{header}</strong> '
            f'<span style="color: var(--muted); font-weight: 400;">— {status}</span>'
        )
        lines.append(
            f'      <p>{blurb} <a href="{base}{c["spec"]}">The spec →</a></p>'
        )
        lines.append("    </div>")
    lines.append("  </div>")
    return "\n".join(lines)


def build_block(manifest):
    return BEGIN_LINE + "\n" + render_grid(manifest) + "\n" + END_LINE


def splice(html, block):
    if BEGIN_MARK not in html or END_MARK not in html:
        raise SystemExit(
            f"markers not found in {TARGET} - add the BEGIN/END "
            f"auto:research-program-grid comments around the grid first"
        )
    b = html.index(BEGIN_MARK)
    line_start = html.rfind("\n", 0, b) + 1  # start of the BEGIN line (keep its indent uniform)
    e = html.index(END_MARK) + len(END_MARK)
    return html[:line_start] + block + html[e:]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify the site is in sync with the manifest; exit 1 if drifted")
    ap.add_argument("--remote", action="store_true",
                    help="force-load the manifest from raw.githubusercontent.com/main "
                         "(ignore any local checkout) — used by the daily run so the site "
                         "reflects the authoritative published manifest")
    args = ap.parse_args()

    manifest, src = load_manifest(remote=args.remote)
    missing = missing_spec_files(manifest, src)
    block = build_block(manifest)
    with open(TARGET, encoding="utf-8") as fh:
        html = fh.read()
    new_html = splice(html, block)
    n = len(manifest["cards"])

    if args.check:
        if missing:
            for cid, spec in missing:
                print(f"MISSING SPEC: card {cid!r} links {spec}, "
                      f"but no such file next to {src}", file=sys.stderr)
            return 1
        if new_html != html:
            print(f"DRIFT: {TARGET} is out of sync with {src}. "
                  f"Run `python scripts/build_patterns_program.py` to regenerate.", file=sys.stderr)
            return 1
        print(f"in sync: {n} cards, source {src}")
        return 0

    if missing:  # regenerate anyway, but never let a broken spec link ship silently
        for cid, spec in missing:
            print(f"WARNING: card {cid!r} links {spec}, but no such file "
                  f"next to {src}", file=sys.stderr)

    if new_html == html:
        print(f"no change: {n} cards already current ({src})")
        return 0
    with open(TARGET, "w", encoding="utf-8") as fh:
        fh.write(new_html)
    print(f"wrote {TARGET}: {n} cards from {src}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
